# Generated by Django 3.2 on 2021-04-26 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('nombreEmpresa', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Consta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionDePedidos.componente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('componentes', models.ManyToManyField(through='appGestionDePedidos.Consta', to='appGestionDePedidos.Componente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precioTotal', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionDePedidos.cliente')),
                ('productos', models.ManyToManyField(through='appGestionDePedidos.Compone', to='appGestionDePedidos.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='consta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionDePedidos.producto'),
        ),
        migrations.AddField(
            model_name='compone',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionDePedidos.pedido'),
        ),
        migrations.AddField(
            model_name='compone',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionDePedidos.producto'),
        ),
    ]
